# https://docs.aws.amazon.com/lambda/latest/dg/go-image.html
# https://gallery.ecr.aws/lambda/provided
#

#old ... FROM fedora:latest

FROM golang:1.21 as builder

# Build the producer_example
WORKDIR /workspace
COPY go.mod .
COPY go.sum .
COPY main.go .
RUN go mod tidy

#RUN go build -tags lambda.norpc -o main main.go
#RUN go build -o main main.go
#RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /app/main
RUN go build -o main main.go

############################
# STEP 2 build a small image
############################
FROM public.ecr.aws/lambda/provided:al2

# Copy our static executable.
COPY --from=builder /workspace/main /lambdaloader

# Run it
ENTRYPOINT ["lambdaloader"]

